### ISSUE TITLE
Faire une doc 

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/gn_module_suivi_habitat_territoire#10]
Install et comment administrer les données

**Comment by camillemonchicourt** [comment]
Pour la partie données, voir https://github.com/PnX-SI/gn_module_suivi_flore_territoire/blob/master/docs/import-data.rst

Pour la partie installation, voir https://github.com/PnX-SI/gn_module_suivi_flore_territoire/blob/master/README.rst

**Comment by cdcvidal** [comment]
Pour l'installation, voir https://github.com/PnX-SI/gn_module_suivi_habitat_territoire/blob/master/README.rst
Pour l'insertion des données, voir https://github.com/PnX-SI/gn_module_suivi_habitat_territoire/blob/master/docs/imports_data.rst et https://github.com/PnX-SI/gn_module_suivi_habitat_territoire/blob/master/data/sht_data.sql.
