### ISSUE TITLE
Appliquer le filtre (commune/organisme/année/habitat) sur la carte

### ISSUE THREAD

**Issue by LeaCBNA** [PnX-SI/gn_module_suivi_habitat_territoire#26]
Lors d'un filtre (organisme, année de visite, commune, habitat) le filtre se fait sur le tableau de gauche et la carte se déplace sur le centroïde des observations correspondantes mais en conservant l'intégralité des points. Ce serait pratique que le filtre s'applique également sur la carte.

**Comment by camillemonchicourt** [comment]
Oui c'est donc un bug non souhaitable.
Le contenu de la carte et de la liste sont censés être filtrés et cohérents.

**Comment by jpm-cbna** [comment]
Le problème est lié la bibliothèque Leaflate Deflate qui permet d'ajouter les markers associés à chaque site. Dans la version 1.3 que nous utilisons, il y a un bug qui empêche la suppression.
En passant la bibliothèque en v2.1.0 ainsi que le package Node `@types/geojson` en version `7946.0.8`, le problème est résolu.

Il faut donc mettre à jour GeoNature car ces packages sont installés au niveau de GeoNature. Lorsqu'il sera possible d'installer des packages directement depuis les modules, il serait intéressant de rapatrier cette installation. Il faut toutefois que le problème rencontré dans le ticket #21 ne reproduise pas.
