### ISSUE TITLE
Corriger fonctionnement du champ "recherche observateur" lors d'ajout nouvelle visite

### ISSUE THREAD

**Issue by LeaCBNA** [PnX-SI/gn_module_suivi_habitat_territoire#27]
Lors de l'ajout d'une nouvelle visite, le champ "rechercher" en haut de liste des observateurs ne semble pas fonctionner (ni dynamiquement ni avec entrée).

**Comment by jpm-cbna** [comment]
Cela fonctionne à nouveau.
Je pense que le problème était lié à une mauvaise configuration de la liste des observateurs.
