### ISSUE TITLE
Ré-appliquer le filtre lors d'un retour (consultation)

### ISSUE THREAD

**Issue by LeaCBNA** [PnX-SI/gn_module_suivi_habitat_territoire#28]
Lors d'une consultation, si on filtre à la commune (par exple) puis que l'on regarde les détails d'une maille puis que l'on souhaite revenir en arrière avec "retour à la liste des sites", le filtre précédemment appliqué est remis à 0. Il serait pratique qu'il reste actif pour éviter de le remettre à chaque fois.

**Comment by jpm-cbna** [comment]
Dans le même ordre d'idée, une remarque de Sophie V. :
"Quand on fait "retour à la liste des sites", la sélection a disparu, il faut à nouveau utiliser les listes déroulantes pour refaire la sélection, ce qui est assez chronophage quand on saisit de nombreuses mailles..."

**Comment by jpm-cbna** [comment]
Cette fonctionnalité a été mise en place en utilisant le LocalStorage.
