### ISSUE TITLE
Corriger l'actualisation du contenu détaillé d'une maille

### ISSUE THREAD

**Issue by LeaCBNA** [PnX-SI/gn_module_suivi_habitat_territoire#29]
Le contenu détaillé d'une maille ne se met pas à jour, exemple : 
Consultation des sites / commune Villaroger -> 3 mailles avec dernière visite en 2021.
Mais lorsqu'on clique sur la maille -> "aucune visite sur ce site" dans informations générales ni détails.

**Comment by LeaCBNA** [comment]
J'ai l'impression que c'est le cas uniquement sur les mailles avec (re)passage en 2021

**Comment by LeaCBNA** [comment]
![pb actualisation 2](https://user-images.githubusercontent.com/78096120/151143931-9c212555-e945-4058-9f2e-8b5af020ddfd.png)

Mais

![pb actualisation 1](https://user-images.githubusercontent.com/78096120/151143960-39545c05-fed0-431c-bef5-ba956e583d86.png)

**Comment by jpm-cbna** [comment]
Le problème en question semble résolu. À tester à nouveau avec la nouvelle version comprenant de nombreuses corrections.

**Comment by jpm-cbna** [comment]
Apparemment, le souci était lié au réseau très lent. Or, il n'y a pas de spiner sur le tableau de la liste de visites et le message "Aucune visite" s'affiche en attendant que les résultats soit télécharger via le web service.
