### ISSUE TITLE
Corriger la duplication des lignes lors de l'export en CSV

### ISSUE THREAD

**Issue by LeaCBNA** [PnX-SI/gn_module_suivi_habitat_territoire#30]
Lors de l'export des données d'une maille en csv (mais pas vérifié si ça le faisait aussi pour les autres formats), la ligne correspondante est dupliquée à l'identique 3 fois.

**Comment by jpm-cbna** [comment]
Le problème était lié à la vue d'export qui réalisé une mauvaise agrégation de certaines données en SQL.
