### ISSUE TITLE
Accorder la couleur des marker à la couleur de la maille sur la carte ?

### ISSUE THREAD

**Issue by LeaCBNA** [PnX-SI/gn_module_suivi_habitat_territoire#31]
Pour une meilleure vue d'ensemble, ou peut-être modifier un peu les couleurs de maille, car la différence entre les rouges des an+1, an+2, an+3 n'est pas très visible lorsque l'on n'a pas les différentes couleurs côte à côte.

**Comment by jpm-cbna** [comment]
Pour améliorer ce fonctionnement, nous avons remplacé les "an+1", "an+2"... pas très compréhensible par l'année considéré. Par ailleurs, les couleurs ont été entièrement remplacées : 
- année courante : bleu
- année courante - 1 : vert
- année courante - 2 : jaune
- année courante - 3 : orange
- année courante - 4 et plus : rouge

Plus les visites sont lointaines plus les géométries des sites sont remplies avec une couleur rouge.

Les couleurs des markers correspondent maintenant à la coloration des géométries dont la transparence est fixe à "0.5".
