### ISSUE TITLE
Documenter intégration de nouvelles données

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_suivi_habitat_territoire#8]
Voir SFT : https://github.com/PnX-SI/gn_module_suivi_flore_territoire/blob/master/docs/import-data.rst

**Comment by cdcvidal** [comment]
Pour la partie données, voir https://github.com/PnX-SI/gn_module_suivi_habitat_territoire/blob/master/docs/import-data.rst
