### ISSUE TITLE
Revoir l'export 

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/gn_module_suivi_habitat_territoire#9]
Les Taxons sont tous dans les même colonnes il faut les avoir dans plusieurs colonnes 

Il faut aussi un export sur l’écran MAP/list avec prise en compte des filtres

**Comment by cdcvidal** [comment]
voir, https://github.com/PnX-SI/gn_module_suivi_habitat_territoire/commit/928aa3bdec18e2a60e0db0b31d4f02ab927eb1e4
